name: demo
version: 1.0.0
config-version: 2
profile: demo
model-paths:
  - models
  - sources
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
target-path: target
clean-targets:
  - target
  - dbt_packages
vars:
  data_diff:
    prod_database: DEMO
    prod_schema: CORE
models:
  demo:
    core:
      +materialized: table
    syncs:
      +materialized: table
