name: 'duckdb_demo'
version: '1.0.0'
config-version: 2

profile: 'duckdb_demo'

vars:
  # configuration for the data-diff tool
  data_diff:
    prod_database: duckdb_demo
    prod_schema: prod

models:
  duckdb_demo:
    core:
      +materialized: table
    syncs:
      +materialized: table