demo:
  target: sf
  outputs:
    sf:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') | as_text }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') | as_text }}"
      database: DEMO
      warehouse: INTEGRATION
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') | as_text }}"
      threads: 24

demo_databricks:
  target: db
  outputs:
    db:
      type: databricks
      catalog: demo
      schema: "{{ env_var('DATABRICKS_DEMO_SCHEMA') | as_text }}"
      host: "{{ env_var('DATABRICKS_DEMO_HOST') }}"
      http_path: "{{ env_var('DATABRICKS_DEMO_PATH') }}"
      token: "{{ env_var('DATABRICKS_DEMO_TOKEN') }}"
      threads: 5


demo_bigquery:
  target: bq
  outputs:
    bq:
      type: bigquery
      method: service-account-json
      project: "{{ env_var('BIGQUERY_DEMO_PROJECT_ID') }}"
      dataset: "{{ env_var('BIGQUERY_DEMO_DATASET') }}"
      threads: 5
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile_json:
        type: "service_account"
        project_id: "{{ env_var('BIGQUERY_DEMO_PROJECT_ID') }}"
        private_key_id: "{{ env_var('BIGQUERY_DEMO_PRIVATE_KEY_ID') }}"
        private_key: "{{ env_var('BIGQUERY_DEMO_PRIVATE_KEY') }}"
        client_email: "{{ env_var('BIGQUERY_DEMO_CLIENT_EMAIL') }}"
        client_id: "{{ env_var('BIGQUERY_DEMO_CLIENT_ID') }}"
        auth_uri: "https://accounts.google.com/o/oauth2/auth"
        token_uri: "https://oauth2.googleapis.com/token"
        auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
        client_x509_cert_url: "{{ env_var('BIGQUERY_DEMO_CLIENT_X509_CERT_URL') }}"
        universe_domain: "googleapis.com"

demo_dremio:
  target: dr
  outputs:
    dr:
      cloud_host: api.dremio.cloud
      cloud_project_id: e94ab14a-43d8-44dd-8f59-cffbb1f0f12f
      pat: "{{ env_var('DREMIO_TOKEN') }}"
      object_storage_source: "Alexey S3"
      # object_storage_path: "alexeydremiobucket.folder2"
      object_storage_path: "{{ 'alexeydremiobucket.' + env_var('DREMIO_FOLDER') }}"
      dremio_space: demo
      dremio_space_folder: no_schema
      threads: 5
      type: dremio
      use_ssl: true
      user: "{{ env_var('DREMIO_USER') }}"

