demo:
  target: redshift
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') | as_text }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"
      role: "{{ env_var('SNOWFLAKE_ROLE') | as_text }}"
      database: DEMO
      warehouse: INTEGRATION
      schema: "{{ env_var('SNOWFLAKE_SCHEMA') | as_text }}"
      threads: 24

    databricks:
      type: databricks
      # catalog: [optional catalog name if you are using Unity Catalog]
      schema: dbt_sung # Required
      host: dbc-3c94f763-f2ee.cloud.databricks.com
      http_path: /sql/1.0/warehouses/1ebc3303fda31656# Required
      token: "{{ env_var('DATABRICKS_TOKEN') | as_text }}"
      threads: 24 

    redshift:
      type: redshift
      host: redshift-cluster-1.cbhakffy7zpc.us-east-1.redshift.amazonaws.com
      user: awsuser
      password: "{{ env_var('REDSHIFT_PASSWORD') | as_text }}"
      dbname: analytics
      schema: analytics
      port: 5439

      # Optional Redshift configs:
      sslmode: prefer
      # role: None
      ra3_node: true 
      autocommit: true 
      threads: 24
      # connect_timeout: None