data_diff_demo:

  target: dev
  outputs:
    dev:
      type: duckdb
      schema: development
      path: 'md:data_diff_demo?motherduck_token={{ env_var("MOTHERDUCK_TOKEN") }}'
      threads: 16

    prod:
      type: duckdb
      schema: production
      path: 'md:data_diff_demo?motherduck_token={{ env_var("MOTHERDUCK_TOKEN") }}'
      threads: 16