version: 2

sources:
  - name: EVENTS
    database: DEMO
    schema: RAW
    tables:
      - name: USER_CREATED
        columns:
          - name: USER_ID
            tests:
              - not_null
              - unique
      - name: ORG_CREATED
        columns:
          - name: ORG_ID
            tests:
              - not_null
              - unique
      - name: SIGNED_IN
      - name: FEATURE_USED
      - name: SUBSCRIPTION_CREATED