version: 2

models:
  - name: dim_orgs
    columns:
      - name: org_id
        tests:
          - not_null
          - unique
        tags: ['primary-key']
  - name: fct_monthly_financials
    columns:
      - name: date_month
        tests:
          - not_null
          - unique
        tags: ['primary-key']
  - name: fct_yearly_financials:
    +meta:
      datafold:
        datadiff:
          slim_diff: diff_when_downstream
    columns:
      - name: date_year
        tests:
          - not_null
          - unique
        tags: ['primary-key']
