version: 2

models:
  - name: dim_orgs
    columns:
      - name: org_id
        tests:
          - not_null
          - unique
        tags: ['primary-key']
    # # example meta filter
    # meta:
    #   datafold:
    #     datadiff:
    #       filter: "created_at >= '2022-05-01'"

  - name: fct_monthly_financials
    columns:
      - name: date_year
        tests:
          - not_null
        tags: ['primary-key']
      - name: date_month
        tests:
          - not_null
          - unique
        tags: ['primary-key']
  - name: fct_yearly_financials
    columns:
      - name: date_year
        tests:
          - not_null
        tags: ['primary-key']
