version: 2

models:
  - name: dim_users
    columns:
      - name: user_id
        tests:
          - not_null
          - unique
        tags: ['primary-key']
  - name: dim_orgs
    columns:
      - name: org_id
        # tests:
          # - not_null
          # - unique
        # tags: ['primary-key']
  - name: fct_monthly_financials
    columns:
      - name: date_month
        tests:
          - not_null
          # - unique
        # tags: ['primary-key']
  - name: fct_yearly_financials
    columns:
      - name: date_year
        tests:
          - not_null
          # - unique
        # tags: ['primary-key']
