name: live monitor data update

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '*/7 * * * *'

jobs:
  run:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install requirements
        run: |
          echo "setuptools<72" > constraints.txt
          export PIP_CONSTRAINT=constraints.txt
          pip install --upgrade pip
          pip install -r datagen/requirements.txt

      - name: regenerate the monitor
        working-directory: datagen
        run: python live_monitor.py
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
